package generation;

class Ressource {
	public static String[] m_firstname = { "abel", "absolon", "achille", "adam", "adolphe", "adrien", "aimé", "alain",
			"albert", "alexandre", "alexis", "alfred", "alphonse", "amaury", "ambroise", "amédée", "anatole", "andré",
			"anselme", "antoine", "apollinaire", "aristide", "armand", "armel", "arnaud", "auguste", "augustin",
			"aurèle", "aurelien", "baptiste", "barnabé", "barthélémy", "basile", "bastien", "baudouin", "benjamin",
			"benoit", "bernard", "bertrand", "blaise", "boniface", "brice", "bruno", "célestin", "cesaire", "césar",
			"charles", "charlot", "christian", "christophe", "clément", "colombain", "constant", "constantin",
			"corentin", "corin", "damien", "daniel", "david", "denis", "dennis", "désiré", "didier", "dieudonné",
			"dimitri", "diodore", "dion", "donat", "donatien", "edgar", "edgard", "edmond", "édouard", "eloi", "émile",
			"émilien", "emmanuel", "eric", "ermenegilde", "étienne", "eugène", "eustache", "évariste", "evrard",
			"fabien", "fabrice", "felicien", "félix", "ferdinand", "fernand", "fiacre", "firmin", "florentin",
			"florian", "franck", "françois", "frédéric", "gabriel", "gaétan", "gaspard", "gaston", "gautier",
			"geoffroi", "georges", "gérald", "gérard", "géraud", "germain", "gervais", "ghislain", "gilbert", "gilles",
			"godelieve", "gratien", "grégoire", "guillaume", "gustave", "guy", "hector", "henri", "herbert", "hercule",
			"hervé", "hilaire", "honoré", "horace", "hubert", "hugues", "humbert", "ignace", "iréné", "isidore",
			"jacques", "jean", "jean-baptiste", "jean-marie", "jeannot", "jérémie", "jérôme", "joachim", "joël",
			"joseph", "josue", "jourdain", "jules", "julien", "juste", "justin", "lambert", "laurent", "lazare",
			"léandre", "léon", "léonard", "léonce", "léopold", "lionel", "loic", "lothaire", "louis", "loup", "luc",
			"lucas", "lucien", "marc", "marcel", "marcellin", "marin", "marius", "martin", "mathieu", "mathis",
			"matthieu", "maurice", "maxime", "maximilien", "michel", "modeste", "modestine", "narcisse", "nazaire",
			"nicholas", "nicodème", "nicolas", "noé", "noel", "odilon", "olivier", "onesime", "papillion", "pascal",
			"paschal", "patrice", "patrick", "paul", "perceval", "philbert", "philibert", "philippe", "pierre",
			"pierrick", "pons", "prosper", "quentin", "rainier", "raoul", "raphaël", "raphael", "raymond", "régis",
			"rémi", "rémy", "renard", "renaud", "rené", "reynaud", "richard", "robert", "roch", "rodolph", "rodolphe",
			"rodrigue", "roger", "roland", "romain", "samuel", "sébastien", "serge", "séverin", "simon", "stéphane",
			"sylvain", "sylvestre", "telesphore", "theirn", "théo", "théodore", "théophile", "thibault", "thierry",
			"thomas", "timothée", "toussaint", "tristan", "ulrich", "urbain", "valentin", "valère", "valéry",
			"vespasien", "victor", "vincent", "xavier", "yann", "yves", "zacharie" };

	public static String[] f_firstname = { "adélaïde", "adèle", "adeline", "adrienne", "agathe", "agnès", "aimée",
			"albertine", "alexandrie", "alice", "aline", "alphonsine", "amarante", "ambre", "amélie", "anaïs",
			"anastasie", "andrée", "angèle", "angeline", "angelique", "anne", "annette", "antoinette", "apolline",
			"ariane", "arianne", "arienne", "arlette", "armelle", "arnaude", "aude", "aurélie", "aurore", "avril",
			"axelle", "barbara", "béatrice", "bénédicte", "benjamine", "benoite", "bernadette", "bernardine", "berthe",
			"blanche", "brigitte", "carine", "carole", "caroline", "catherine", "cécile", "céleste", "célestine",
			"céline", "cerise", "chantal", "chanté", "charline", "charlotte", "chloé", "christelle", "christiane",
			"christianne", "christine", "claire", "clarice", "clarisse", "claudette", "claudine", "clémence",
			"clementine", "clothilde", "colette", "constance", "corinne", "cosette", "cunégonde", "danièle", "danielle",
			"delphine", "denise", "désirée", "diane", "dianne", "dieudonnée", "donatienne", "doriane", "dorothée",
			"édith", "edwige", "eléonore", "éliane", "elisabeth", "élise", "élodie", "éloise", "emeline", "émilie",
			"emma", "emmanuelle", "esmée", "esther", "eugénie", "eulalie", "eve", "evette", "fabienne", "fabiola",
			"faustine", "félicie", "felicienne", "fernande", "fifi", "flavie", "florette", "florianne", "francine",
			"françoise", "frédérique", "gabrielle", "gaetane", "geneviève", "georgette", "georgine", "germaine",
			"gervaise", "ghislaine", "gigi", "gilberte", "gisèle", "giselle", "gisselle", "gwenaelle", "hannah",
			"hélène", "héloïse", "henriette", "hermine", "honorine", "hortense", "hyacinthe", "inès", "irène", "irénée",
			"isabel", "isabelle", "jacinthe", "jacqueline", "jeanine", "jeanne", "jeannette", "jeannine", "joceline",
			"joelle", "jolie", "josée", "josèphe", "joséphine", "josette", "josiane", "judith", "juliane", "julie",
			"julienne", "juliette", "justine", "laure", "laurence", "laurentine", "laurette", "léa", "léonie", "léonne",
			"léontine", "liane", "lisette", "louise", "luce", "lucie", "lucienne", "lucile", "lucille", "lucinde",
			"lucrece", "lunete", "lydie", "madeleine", "madeline", "manon", "marceline", "marcelle", "marcellette",
			"marcelline", "margot", "marguerite", "marianne", "marie", "marielle", "mariette", "marine", "marise",
			"marthe", "martine", "mathilde", "maximilienne", "mélanie", "mélissa", "michèle", "micheline", "michelle",
			"mignon", "mirabelle", "mireille", "monique", "morgaine", "morgane", "muriel", "myriam", "nadia", "nadine",
			"natalie", "nathalie", "nicole", "nicolette", "nina", "ninette", "ninon", "noella", "noelle", "noémie",
			"océane", "odette", "odile", "olivie", "olympe", "oriane", "orianne", "ouida", "pascale", "pascaline",
			"paule", "paulette", "pauline", "pénélope", "perrine", "philippine", "placide", "rachel", "raymonde",
			"rébecca", "régine", "reine", "renée", "rochelle", "rolande", "romaine", "rosalie", "rose", "roselle",
			"rosemonde", "rosette", "rosine", "roxane", "roxanne", "sabine", "salomé", "sandrine", "sarah",
			"sébastienne", "seraphine", "sévérine", "sibylle", "sidonie", "simone", "solange", "sophie", "stéphanie",
			"suzanne", "suzette", "sybille", "sylvaine", "sylviane", "sylvianne", "sylvie", "tatienne", "thérèse",
			"toinette", "valentine", "valérie", "véronique", "victoire", "victorine", "vienne", "violette", "virginie",
			"vivienne", "yolande", "yseult", "yvette", "yvonne", "zephyrine", "zoé" };

	public static String[] lastname = { "Bernard", "Thomas", "Petit", "Robert", "Richard", "Durand", "Dubois",
			"Moreau", "Laurent", "Simon", "Michel", "Lefebvre", "Leroy", "Roux", "David", "Bertrand", "Morel",
			"Fournier", "Girard", "Bonnet", "Dupont", "Lambert", "Fontaine", "Rousseau", "Vincent", "Muller", "Lefevre",
			"Faure", "Andre", "Mercier", "Blanc", "Guerin", "Boyer", "Garnier", "Chevalier", "Francois", "Legrand",
			"Gauthier", "Perrin", "Robin", "Clement", "Morin", "Nicolas", "Henry", "Roussel", "Mathieu", "Gautier",
			"Masson", "Marchand", "Duval", "Denis", "Dumont", "Marie", "Lemaire", "Noel", "Meyer", "Dufour", "Meunier",
			"Brun", "Blanchard", "Giraud", "Joly", "Riviere", "Lucas", "Brunet", "Gaillard", "Barbier", "Arnaud",
			"Martinez", "Gerard", "Roche", "Renard", "Schmitt", "Roy", "Leroux", "Colin", "Vidal", "Caron", "Picard",
			"Roger", "Fabre", "Aubert", "Lemoine", "Renaud", "Dumas", "Lacroix", "Olivier", "Philippe", "Bourgeois",
			"Pierre", "Benoit", "Rey", "Leclerc", "Payet", "Rolland", "Leclercq", "Guillaume", "Lecomte", "Lopez",
			"Jean", "Dupuy", "Guillot", "Hubert", "Berger", "Carpentier", "Sanchez", "Dupuis", "Moulin", "Louis",
			"Deschamps", "Huet", "Vasseur", "Boucher", "Fleury", "Royer", "Klein", "Jacquet", "Adam", "Paris",
			"Poirier", "Marty", "Aubry", "Guyot", "Carre", "Charles", "Renault", "Charpentier", "Menard", "Maillard",
			"Baron", "Bertin", "Bailly", "Herve", "Schneider", "Fernandez", "Le Gall", "Collet", "Leger", "Bouvier",
			"Julien", "Prevost", "Millet", "Perrot", "Daniel", "Le Roux", "Cousin", "Germain", "Breton", "Besson",
			"Langlois", "Remy", "Le Goff", "Pelletier", "Lévêque", "Perrier", "Leblanc", "Barre", "Lebrun", "Marchal",
			"Weber", "Mallet", "Hamon", "Boulanger", "Jacob", "Monnier", "Michaud", "Rodriguez", "Guichard", "Gillet",
			"Etienne", "Grondin", "Poulain", "Tessier", "Chevallier", "Collin", "Chauvin", "Da Silva", "Bouchet", "Gay",
			"Lemaitre", "Benard", "Marechal", "Humbert", "Reynaud", "Antoine", "Hoarau", "Perret", "Barthelemy",
			"Cordier", "Pichon", "Lejeune", "Gilbert", "Lamy", "Delaunay", "Pasquier", "Carlier", "Laporte" };

	public static String[] negativeComment = { "le projet va vers une impasse", "comme hier",
			"les choix technologiques sont mauvais", "il ne fait pas beau", "il fait beau et on a trop de travail",
			"il manque des sous", "je suis mal payé pour ce travail", "je ne suis pas considéré" };

	public static String[] positiveComment = { "cool", "bonne journée", "projet intéressant", "bonne journée",
			"le client est satisfait", "le travail est motivant", "j'ai de l'avance sur le projet",
			"les moyens sont mis", "très bonne cohésion d'équipe", "comme hier", "belle journée", "il fait beau" };
	
	public static String[] comment = { "la Routine", "du travail", "no comment", "encore une journée de plus",
			"comme hier", "le projet suis son cours", "il fait beau dehors" };

}