package com.tactfactory.nikoniko.utils;

class Ressource {
    public static String[] m_firstname={
        "abel", 
        "absolon", "achille", "adam", "adolphe", "adrien", 
        "aimé", "alain", "albert", "alexandre", "alexis", 
        "alfred", "alphonse", "amaury", "ambroise", "amédée", 
        "anatole", "andré", "anselme", "antoine", "apollinaire", 
        "aristide", "armand", "armel", "arnaud", "auguste", 
        "augustin", "aurèle", "aurelien", "baptiste", "barnabé", 
        "barthélémy", "basile", "bastien", "baudouin", "benjamin", 
        "benoit", "bernard", "bertrand", "blaise", "boniface", 
        "brice", "bruno", "célestin", "cesaire", "césar", 
        "charles", "charlot", "christian", "christophe", "clément", 
        "colombain", "constant", "constantin", "corentin", "corin", 
        "damien", "daniel", "david", "denis", "dennis", 
        "désiré", "didier", "dieudonné", "dimitri", "diodore", 
        "dion", "donat", "donatien", "edgar", "edgard", 
        "edmond", "édouard", "eloi", "émile", "émilien", 
        "emmanuel", "eric", "ermenegilde", "étienne", "eugène", 
        "eustache", "évariste", "evrard", "fabien", "fabrice", 
        "felicien", "félix", "ferdinand", "fernand", "fiacre", 
        "firmin", "florentin", "florian", "franck", "françois", 
        "frédéric", "gabriel", "gaétan", "gaspard", "gaston", 
        "gautier", "geoffroi", "georges", "gérald", "gérard", 
        "géraud", "germain", "gervais", "ghislain", "gilbert", 
        "gilles", "godelieve", "gratien", "grégoire", "guillaume", 
        "gustave", "guy", "hector", "henri", "herbert", 
        "hercule", "hervé", "hilaire", "honoré", "horace", 
        "hubert", "hugues", "humbert", "ignace", "iréné", 
        "isidore", "jacques", "jean", "jean-baptiste", "jean-marie", 
        "jeannot", "jérémie", "jérôme", "joachim", "joël", 
        "joseph", "josue", "jourdain", "jules", "julien", 
        "juste", "justin", "lambert", "laurent", "lazare", 
        "léandre", "léon", "léonard", "léonce", "léopold", 
        "lionel", "loic", "lothaire", "louis", "loup", 
        "luc", "lucas", "lucien", "marc", "marcel", 
        "marcellin", "marin", "marius", "martin", "mathieu", 
        "mathis", "matthieu", "maurice", "maxime", "maximilien", 
        "michel", "modeste", "modestine", "narcisse", "nazaire", 
        "nicholas", "nicodème", "nicolas", "noé", "noel", 
        "odilon", "olivier", "onesime", "papillion", "pascal", 
        "paschal", "patrice", "patrick", "paul", "perceval", 
        "philbert", "philibert", "philippe", "pierre", "pierrick", 
        "pons", "prosper", "quentin", "rainier", "raoul", 
        "raphaël", "raphael", "raymond", "régis", "rémi", 
        "rémy", "renard", "renaud", "rené", "reynaud", 
        "richard", "robert", "roch", "rodolph", "rodolphe", 
        "rodrigue", "roger", "roland", "romain", "samuel", 
        "sébastien", "serge", "séverin", "simon", "stéphane", 
        "sylvain", "sylvestre", "telesphore", "theirn", "théo", 
        "théodore", "théophile", "thibault", "thierry", "thomas", 
        "timothée", "toussaint", "tristan", "ulrich", "urbain", 
        "valentin", "valère", "valéry", "vespasien", "victor", 
        "vincent", "xavier", "yann", "yves", "zacharie", 
    };
    public static String[] m_lastname={
        "Bernard", 
        "Thomas", "Petit", "Robert", "Richard", "Durand", 
        "Dubois", "Moreau", "Laurent", "Simon", "Michel", 
        "Lefebvre", "Leroy", "Roux", "David", "Bertrand", 
        "Morel", "Fournier", "Girard", "Bonnet", "Dupont", 
        "Lambert", "Fontaine", "Rousseau", "Vincent", "Muller", 
        "Lefevre", "Faure", "Andre", "Mercier", "Blanc", 
        "Guerin", "Boyer", "Garnier", "Chevalier", "Francois", 
        "Legrand", "Gauthier", "Perrin", "Robin", "Clement", 
        "Morin", "Nicolas", "Henry", "Roussel", "Mathieu", 
        "Gautier", "Masson", "Marchand", "Duval", "Denis", 
        "Dumont", "Marie", "Lemaire", "Noel", "Meyer", 
        "Dufour", "Meunier", "Brun", "Blanchard", "Giraud", 
        "Joly", "Riviere", "Lucas", "Brunet", "Gaillard", 
        "Barbier", "Arnaud", "Martinez", "Gerard", "Roche", 
        "Renard", "Schmitt", "Roy", "Leroux", "Colin", 
        "Vidal", "Caron", "Picard", "Roger", "Fabre", 
        "Aubert", "Lemoine", "Renaud", "Dumas", "Lacroix", 
        "Olivier", "Philippe", "Bourgeois", "Pierre", "Benoit", 
        "Rey", "Leclerc", "Payet", "Rolland", "Leclercq", 
        "Guillaume", "Lecomte", "Lopez", "Jean", "Dupuy", 
        "Guillot", "Hubert", "Berger", "Carpentier", "Sanchez", 
        "Dupuis", "Moulin", "Louis", "Deschamps", "Huet", 
        "Vasseur", "Boucher", "Fleury", "Royer", "Klein", 
        "Jacquet", "Adam", "Paris", "Poirier", "Marty", 
        "Aubry", "Guyot", "Carre", "Charles", "Renault", 
        "Charpentier", "Menard", "Maillard", "Baron", "Bertin", 
        "Bailly", "Herve", "Schneider", "Fernandez", "Le Gall", 
        "Collet", "Leger", "Bouvier", "Julien", "Prevost", 
        "Millet", "Perrot", "Daniel", "Le Roux", "Cousin", 
        "Germain", "Breton", "Besson", "Langlois", "Remy", 
        "Le Goff", "Pelletier", "Lévêque", "Perrier", "Leblanc", 
        "Barre", "Lebrun", "Marchal", "Weber", "Mallet", 
        "Hamon", "Boulanger", "Jacob", "Monnier", "Michaud", 
        "Rodriguez", "Guichard", "Gillet", "Etienne", "Grondin", 
        "Poulain", "Tessier", "Chevallier", "Collin", "Chauvin", 
        "Da Silva", "Bouchet", "Gay", "Lemaitre", "Benard", 
        "Marechal", "Humbert", "Reynaud", "Antoine", "Hoarau", 
        "Perret", "Barthelemy", "Cordier", "Pichon", "Lejeune", 
        "Gilbert", "Lamy", "Delaunay", "Pasquier", "Carlier", 
        "Laporte"};
}
